---

- name: Update {{ application_name }} server

  hosts:
    - all

  vars_files:
    - env_vars/base.yml
    - env_vars/testing.yml

  roles:
    - web

  tasks:
    - shell: echo "Restarting Apache..."
